apply_sql = """
CREATE TABLE routingLoadBalancing (
  id INT UNSIGNED auto_increment NOT NULL,
  merchantId INT UNSIGNED NOT NULL,
  accountId INT UNSIGNED NOT NULL,
  minExpectedTxn INT UNSIGNED NULL,
  maxExpectedTxn INT UNSIGNED NULL,
  TxnSharePG1 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG2 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG5 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG6 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG7 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG8 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG9 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG11 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG12 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG13 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG14 INT UNSIGNED DEFAULT 0 NULL,
  TxnSharePG15 INT UNSIGNED DEFAULT 0 NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  recUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_mid_aid_idx` (`merchantId`,`accountId`)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1;
"""

rollback_sql = "DROP TABLE IF EXISTS routingLoadBalancing"

migrations = {
    "apply": apply_sql,
    "rollback": rollback_sql
}
